choiwono/pouch

- src/main/java/my/examples/pouch/domain/Message.java
- src/main/resources/data.sql
> #19.03.14 Message Entity 수정

- pom.xml
- src/main/java/my/examples/pouch/config/SecurityConfig.java
- src/main/java/my/examples/pouch/controller/crawling/CrawlingController.java
- src/main/java/my/examples/pouch/domain/Account.java
- src/main/java/my/examples/pouch/domain/AccountCategory.java
- src/main/java/my/examples/pouch/domain/Tag.java
- src/main/resources/data.sql
- src/test/java/my/examples/pouch/repository/TagRepositoryTest.java
> #Domain 수정 및 샘플 데이터 삽입

- src/main/java/my/examples/pouch/controller/crawling/CrawlingController.java
- src/main/java/my/examples/pouch/domain/Account.java
- src/main/java/my/examples/pouch/domain/AccountCategory.java
- src/main/java/my/examples/pouch/domain/Board.java
- src/main/java/my/examples/pouch/repository/AccountCategoryRepository.java
- src/main/java/my/examples/pouch/service/AccountCategoryService.java
- src/main/java/my/examples/pouch/service/BoardService.java
- src/main/resources/templates/fragments/header.html
> #19.03.19 크롤링, entity, 데이터 수정

- src/main/java/my/examples/pouch/domain/Account.java
- src/main/java/my/examples/pouch/domain/AccountTheme.java
- src/main/resources/data.sql
> #19.03.20 데이터 sql 및 entity 수정

- src/main/java/my/examples/pouch/dto/CustomTag.java
- src/main/java/my/examples/pouch/repository/LinkRepository.java
- src/main/java/my/examples/pouch/service/TagService.java
- src/main/resources/static/js/common.js
- src/main/resources/templates/pouch/list.html
> #19.03.27 tag 관련 ajax 수정

- src/main/java/my/examples/pouch/controller/api/TagApiController.java
- src/main/java/my/examples/pouch/dto/CustomTagItem.java
- src/main/resources/static/css/common.css
- src/main/resources/static/js/common.js
- src/main/resources/templates/pouch/list.html
> #19.03.29 tag 추가 완료!!

- src/main/java/my/examples/pouch/config/SecurityConfig.java
- src/main/java/my/examples/pouch/controller/MainController.java
19.04.01 security config 설정 변경
> #19.04.01 security config 설정 변경

- src/main/java/my/examples/pouch/repository/CategoryRepository.java
- src/main/java/my/examples/pouch/repository/custom/CategoryRepositoryCustom.java
- src/main/java/my/examples/pouch/repository/custom/CategoryRepositoryImpl.java
- src/main/java/my/examples/pouch/service/TagService.java
> # tag Service 수정

- src/main/java/my/examples/pouch/config/SecurityConfig.java
- src/main/java/my/examples/pouch/controller/CategoryController.java
- src/main/java/my/examples/pouch/controller/LinkController.java
- src/main/java/my/examples/pouch/controller/crawling/CrawlingController.java
- src/main/resources/templates/fragments/config.html
- src/main/resources/templates/index.html
> #19.04.11 리팩토링

- backend/src/main/java/my/examples/pouch/config/handler/AuthSuccessHandler.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/Account/Join.vue
- frontend/src/components/Account/Login.vue
- frontend/src/components/HelloWorld.vue
- frontend/src/components/layout/Footer.vue
- frontend/src/components/layout/Header.vue
- frontend/src/main.js
- frontend/src/router/index.js
- pouch/src/main/resources/templates/index.html
> #19.04.12 boiler plate 설정 수정

- backend/src/main/java/my/examples/pouch/config/handler/AuthSuccessHandler.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/Account/Join.vue
- frontend/src/components/Account/Login.vue
- frontend/src/components/HelloWorld.vue
- frontend/src/components/layout/Footer.vue
- frontend/src/components/layout/Header.vue
- frontend/src/main.js
- frontend/src/router/index.js
- pouch/src/main/resources/templates/index.html
> #19.04.12 파일 수정완료

- backend/src/main/java/my/examples/pouch/config/SecurityConfig.java
- backend/src/main/java/my/examples/pouch/config/handler/AuthSuccessHandler.java
- frontend/package.json
- frontend/src/components/Account/Join.vue
- frontend/src/components/Account/Login.vue
> #19.04.14 security 설정변경

- backend/src/main/java/my/examples/pouch/controller/api/AccountController.java
- backend/src/main/java/my/examples/pouch/controller/api/TagController.java
> #19.04.17 파일이름 변경

- backend/src/main/java/my/examples/pouch/config/SecurityConfig.java
- backend/src/main/java/my/examples/pouch/controller/api/CategoriesController.java
- backend/src/main/java/my/examples/pouch/repository/CategoryRepository.java
- backend/src/main/java/my/examples/pouch/service/CategoryService.java
- frontend/src/components/Account/Login.vue
- frontend/src/components/Home.vue
- frontend/src/components/layout/Header.vue
> #19.04.18 main 및 header 변경

- backend/src/main/java/my/examples/pouch/controller/api/CategoriesController.java
- backend/src/main/java/my/examples/pouch/controller/crawling/CrawlingController.java
- backend/src/main/java/my/examples/pouch/dto/CustomLink.java
- backend/src/main/java/my/examples/pouch/service/CategoryService.java
- frontend/src/components/Home.vue
- frontend/src/components/layout/Header.vue
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/store.js
19.04.19 vuex 추가, 카테고리 및 링크 추가
> #19.04.19 vuex 추가, 카테고리 및 링크 추가

- frontend/src/components/Contents/Search.vue
- frontend/src/components/layout/Header.vue
- frontend/src/router/index.js
> #190419 검색 기능

- backend/src/main/java/my/examples/pouch/controller/api/AccountController.java
- frontend/src/components/Account/Join.vue
- frontend/src/components/Account/Login.vue
- frontend/src/components/Contents/Search.vue
- frontend/src/components/Home.vue
- frontend/src/components/layout/Header.vue
- frontend/src/router/index.js
> #19.04.22 회원가입(작업중)

- backend/src/main/java/my/examples/pouch/config/SecurityConfig.java
- backend/src/main/java/my/examples/pouch/controller/api/AccountController.java
- backend/src/main/java/my/examples/pouch/dto/Joinform.java
- frontend/src/components/Account/Join.vue
> #19.04.24 회원가입

- backend/src/main/java/my/examples/pouch/controller/api/AccountController.java
- backend/src/main/java/my/examples/pouch/controller/api/CategoriesController.java
- backend/src/main/java/my/examples/pouch/domain/Account.java
- backend/src/main/java/my/examples/pouch/domain/AccountTheme.java
- backend/src/main/java/my/examples/pouch/domain/Category.java
- backend/src/main/java/my/examples/pouch/domain/Link.java
- backend/src/main/java/my/examples/pouch/domain/Message.java
- backend/src/main/java/my/examples/pouch/domain/MessageOption.java
- backend/src/main/java/my/examples/pouch/domain/Tag.java
- backend/src/main/java/my/examples/pouch/repository/CategoryRepository.java
- backend/src/main/java/my/examples/pouch/repository/LinkRepository.java
- backend/src/main/java/my/examples/pouch/service/CategoryService.java
- backend/src/main/java/my/examples/pouch/service/EmailService.java
- backend/src/main/java/my/examples/pouch/service/LinkService.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Account/FindPswd.vue
- frontend/src/components/Contents/Categories.vue
> #190502 다른 유저 파우치 가져오기

- backend/src/main/java/my/examples/pouch/config/MailConfig.java
- backend/src/main/java/my/examples/pouch/controller/api/AccountController.java
- backend/src/main/resources/application.properties
#19.05.09 application properties 수정
> #19.05.09 application properties 수정

- backend/src/main/java/my/examples/pouch/controller/api/AccountController.java
- backend/src/main/java/my/examples/pouch/controller/api/CategoriesController.java
- backend/src/main/java/my/examples/pouch/controller/api/LinkController.java
- backend/src/main/java/my/examples/pouch/service/CategoryService.java
- backend/src/main/java/my/examples/pouch/service/serviceImpl/CategoryServiceImpl.java
- frontend/src/components/Contents/Categories.vue
> #190510 다른 유저의 링크 저장하기 (작업중)

- backend/src/main/java/my/examples/pouch/controller/api/LinkController.java
> #190514 jenkins test

- backend/src/main/java/my/examples/pouch/controller/api/LinkController.java
> # 190514 jenkins test 2

- backend/src/main/java/my/examples/pouch/controller/IndexController.java
- backend/src/main/java/my/examples/pouch/controller/api/AccountController.java
- backend/src/main/java/my/examples/pouch/controller/api/CategoriesController.java
- backend/src/main/java/my/examples/pouch/domain/Message.java
- backend/src/main/java/my/examples/pouch/repository/MessageRepository.java
- backend/src/main/java/my/examples/pouch/service/MessageService.java
- backend/src/main/java/my/examples/pouch/service/serviceImpl/MessageServiceImpl.java
- backend/src/main/resources/data.sql
- frontend/index.html
- frontend/src/components/Account/Join.vue
- frontend/src/components/Contents/Categories.vue
> # 19.05.21 공유 기능 (작업중)

- frontend/src/components/Contents/Categories.vue
> # jenkins test2
